### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by saschagysel** [danilopolani/filament-plausible-widget#2]
I am getting a composer error while trying to install the widget on a fully updated Laravel 9 / Filament 2 installation:

`  Problem 1
    - Root composer.json requires danilopolani/filament-plausible-widget ^2.0 -> satisfiable by danilopolani/filament-plausible-widget[v2.0.0, 2.x-dev].
    - danilopolani/filament-plausible-widget[v2.0.0, ..., 2.x-dev] require illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require danilopolani/filament-plausible-widget:*" to figure out if any version is installable, or "composer require danilopolani/filament-plausible-widget:^2.1" if you know which you need.`

**Comment by danilopolani** [comment]
Hey, thank you for reaching out! I'm going to add the support for Laravel 9 by tomorrow, hopefully this evening 😄

**Comment by saschagysel** [comment]
Thanks a lot :-)

**Comment by danilopolani** [comment]
Version [`2.0.1`](https://github.com/danilopolani/filament-plausible-widget/releases/tag/v2.0.1) released with support for Dark Mode too!

**Comment by saschagysel** [comment]
Hey, I still get this error when trying to install the widget:

`Root composer.json requires danilopolani/filament-plausible-widget ^2.0 -> satisfiable by danilopolani/filament-plausible-widget[v2.0.0, v2.0.1, 2.x-dev].
    - danilopolani/filament-plausible-widget[v2.0.0, ..., 2.x-dev] require illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require danilopolani/filament-plausible-widget:*" to figure out if any version is installable, or "composer require danilopolani/filament-plausible-widget:^2.1" if you know which you need.`

**Comment by danilopolani** [comment]
> Hey, I still get this error when trying to install the widget:
> 
> `Root composer.json requires danilopolani/filament-plausible-widget ^2.0 -> satisfiable by danilopolani/filament-plausible-widget[v2.0.0, v2.0.1, 2.x-dev]. - danilopolani/filament-plausible-widget[v2.0.0, ..., 2.x-dev] require illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require danilopolani/filament-plausible-widget:*" to figure out if any version is installable, or "composer require danilopolani/filament-plausible-widget:^2.1" if you know which you need.`

Hey, sorry I f*cked up the previous release 🤦 Can you try again now? `v2.0.2` should fix it. Sorry!

**Comment by saschagysel** [comment]
Works like a charm, thanks.
